spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/catch_table
    username: developer
    password: 12345

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true